apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: your-registry/your-image:tag
        ports:
        - containerPort: 80
        # Add additional container configurations if needed
        # env:
        # - name: ENV_VARIABLE
        #   value: value
---
apiVersion: v1
kind: Service
metadata:
 
