apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  namespace: default  # You can specify a different namespace if needed
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-pod
        image: nginx:latest  # Replace with the desired container image
        ports:
        - containerPort: 80
